version: "2"

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=dev-db-password
      - POSTGRES_USER=dev-db-user
      - POSTGRES_DB=dev-db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
