/* tslint:disable */
/* eslint-disable */
/**
 * Weather Forecast and Traffic Monitoring
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *
 *
 * @export
 * @interface ImageMetadata
 */
export interface ImageMetadata {
  /**
   * @type {number}
   * @memberof ImageMetadata
   */
  width?: number;

  /**
   * @type {number}
   * @memberof ImageMetadata
   */
  height?: number;

  /**
   * @type {string}
   * @memberof ImageMetadata
   */
  md5?: string;
}
