/* tslint:disable */
/* eslint-disable */
/**
 * Weather Forecast and Traffic Monitoring
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *
 *
 * @export
 * @interface StatusesResponse
 */
export interface StatusesResponse {
  /**
   * @type {string}
   * @memberof StatusesResponse
   */
  main: StatusesResponseMainEnum;

  /**
   * @type {string}
   * @memberof StatusesResponse
   */
  db: StatusesResponseDbEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum StatusesResponseMainEnum {
  OK = "OK",
  DOWN = "DOWN",
}
/**
 * @export
 * @enum {string}
 */
export enum StatusesResponseDbEnum {
  OK = "OK",
  DOWN = "DOWN",
}
