/* tslint:disable */
/* eslint-disable */
/**
 * Weather Forecast and Traffic Monitoring
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *
 *
 * @export
 * @interface TimeSeriesMostQueriedResponse
 */
export interface TimeSeriesMostQueriedResponse {
  /**
   * Queries type, eg \"traffic-camera
   *
   * @type {string}
   * @memberof TimeSeriesMostQueriedResponse
   */
  type: string;

  /**
   * Queried parameter's value
   *
   * @type {string}
   * @memberof TimeSeriesMostQueriedResponse
   */
  selectedDateTime: string;
}
