/* tslint:disable */
/* eslint-disable */
/**
 * Weather Forecast and Traffic Monitoring
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *
 *
 * @export
 * @interface TopQueriedParameter
 */
export interface TopQueriedParameter {
  /**
   * Queried parameter's value
   *
   * @type {string}
   * @memberof TopQueriedParameter
   */
  queriedParameterValue: string;

  /**
   * Query received count
   *
   * @type {number}
   * @memberof TopQueriedParameter
   */
  count: number;
}
