/* tslint:disable */
/* eslint-disable */
/**
 * Weather Forecast and Traffic Monitoring
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { TopQueriedParameter } from "./top-queried-parameter";
/**
 *
 *
 * @export
 * @interface TopQueriedParameterResponse
 */
export interface TopQueriedParameterResponse {
  /**
   * @type {Array<TopQueriedParameter>}
   * @memberof TopQueriedParameterResponse
   */
  topQueriedParameters: Array<TopQueriedParameter>;
}
