/* tslint:disable */
/* eslint-disable */
/**
 * Weather Forecast and Traffic Monitoring
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { GeoLocation } from './geo-location';
import { Image } from './image';
 /**
 * 
 *
 * @export
 * @interface TrafficCamData
 */
export interface TrafficCamData {

    /**
     * @type {string}
     * @memberof TrafficCamData
     */
    cameraId: string;

    /**
     * @type {string}
     * @memberof TrafficCamData
     */
    cursor: string;

    /**
     * @type {Image}
     * @memberof TrafficCamData
     */
    image: Image;

    /**
     * @type {GeoLocation}
     * @memberof TrafficCamData
     */
    location: GeoLocation;
}
