/* tslint:disable */
/* eslint-disable */
/**
 * Weather Forecast and Traffic Monitoring
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import globalAxios, {
  AxiosResponse,
  AxiosInstance,
  AxiosRequestConfig,
} from "axios";
import { Configuration } from "../configuration";
// Some imports not used depending on template conditions
// @ts-ignore
import {
  BASE_PATH,
  COLLECTION_FORMATS,
  RequestArgs,
  BaseAPI,
  RequiredError,
} from "../base";
import { TimeSeriesMostQueriedResponse } from "../models";
import { TopQueriedParameterResponse } from "../models";
/**
 * ReportingApi - axios parameter creator
 * @export
 */
export const ReportingApiAxiosParamCreator = function (
  configuration?: Configuration,
) {
  return {
    /**
     *
     * @param {string} start date time iso string
     * @param {string} end date time iso string
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    reportingControllerHighestQueriedParamWithMovingOneHourBlock: async (
      start: string,
      end: string,
      options: AxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'start' is not null or undefined
      if (start === null || start === undefined) {
        throw new RequiredError(
          "start",
          "Required parameter start was null or undefined when calling reportingControllerHighestQueriedParamWithMovingOneHourBlock.",
        );
      }
      // verify required parameter 'end' is not null or undefined
      if (end === null || end === undefined) {
        throw new RequiredError(
          "end",
          "Required parameter end was null or undefined when calling reportingControllerHighestQueriedParamWithMovingOneHourBlock.",
        );
      }
      const localVarPath = `/reporting/most-queried/traffic-camera-datetime`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, "https://example.com");
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }
      const localVarRequestOptions: AxiosRequestConfig = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      if (start !== undefined) {
        localVarQueryParameter["start"] = start;
      }

      if (end !== undefined) {
        localVarQueryParameter["end"] = end;
      }

      const query = new URLSearchParams(localVarUrlObj.search);
      for (const key in localVarQueryParameter) {
        query.set(key, localVarQueryParameter[key]);
      }
      for (const key in options.params) {
        query.set(key, options.params[key]);
      }
      localVarUrlObj.search = new URLSearchParams(query).toString();
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url:
          localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    reportingControllerRecentQueries: async (
      options: AxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/reporting/recent/traffic-camera-datetime`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, "https://example.com");
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }
      const localVarRequestOptions: AxiosRequestConfig = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      const query = new URLSearchParams(localVarUrlObj.search);
      for (const key in localVarQueryParameter) {
        query.set(key, localVarQueryParameter[key]);
      }
      for (const key in options.params) {
        query.set(key, options.params[key]);
      }
      localVarUrlObj.search = new URLSearchParams(query).toString();
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url:
          localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {string} start
     * @param {string} end
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    reportingControllerTopQueries: async (
      start: string,
      end: string,
      options: AxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'start' is not null or undefined
      if (start === null || start === undefined) {
        throw new RequiredError(
          "start",
          "Required parameter start was null or undefined when calling reportingControllerTopQueries.",
        );
      }
      // verify required parameter 'end' is not null or undefined
      if (end === null || end === undefined) {
        throw new RequiredError(
          "end",
          "Required parameter end was null or undefined when calling reportingControllerTopQueries.",
        );
      }
      const localVarPath = `/reporting/top/traffic-camera-datetime`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, "https://example.com");
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }
      const localVarRequestOptions: AxiosRequestConfig = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      if (start !== undefined) {
        localVarQueryParameter["start"] = start;
      }

      if (end !== undefined) {
        localVarQueryParameter["end"] = end;
      }

      const query = new URLSearchParams(localVarUrlObj.search);
      for (const key in localVarQueryParameter) {
        query.set(key, localVarQueryParameter[key]);
      }
      for (const key in options.params) {
        query.set(key, options.params[key]);
      }
      localVarUrlObj.search = new URLSearchParams(query).toString();
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url:
          localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * ReportingApi - functional programming interface
 * @export
 */
export const ReportingApiFp = function (configuration?: Configuration) {
  return {
    /**
     *
     * @param {string} start date time iso string
     * @param {string} end date time iso string
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async reportingControllerHighestQueriedParamWithMovingOneHourBlock(
      start: string,
      end: string,
      options?: AxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => Promise<AxiosResponse<TimeSeriesMostQueriedResponse>>
    > {
      const localVarAxiosArgs = await ReportingApiAxiosParamCreator(
        configuration,
      ).reportingControllerHighestQueriedParamWithMovingOneHourBlock(
        start,
        end,
        options,
      );
      return (
        axios: AxiosInstance = globalAxios,
        basePath: string = BASE_PATH,
      ) => {
        const axiosRequestArgs: AxiosRequestConfig = {
          ...localVarAxiosArgs.options,
          url: basePath + localVarAxiosArgs.url,
        };
        return axios.request(axiosRequestArgs);
      };
    },
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async reportingControllerRecentQueries(
      options?: AxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => Promise<AxiosResponse<TimeSeriesMostQueriedResponse>>
    > {
      const localVarAxiosArgs =
        await ReportingApiAxiosParamCreator(
          configuration,
        ).reportingControllerRecentQueries(options);
      return (
        axios: AxiosInstance = globalAxios,
        basePath: string = BASE_PATH,
      ) => {
        const axiosRequestArgs: AxiosRequestConfig = {
          ...localVarAxiosArgs.options,
          url: basePath + localVarAxiosArgs.url,
        };
        return axios.request(axiosRequestArgs);
      };
    },
    /**
     *
     * @param {string} start
     * @param {string} end
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async reportingControllerTopQueries(
      start: string,
      end: string,
      options?: AxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => Promise<AxiosResponse<TopQueriedParameterResponse>>
    > {
      const localVarAxiosArgs = await ReportingApiAxiosParamCreator(
        configuration,
      ).reportingControllerTopQueries(start, end, options);
      return (
        axios: AxiosInstance = globalAxios,
        basePath: string = BASE_PATH,
      ) => {
        const axiosRequestArgs: AxiosRequestConfig = {
          ...localVarAxiosArgs.options,
          url: basePath + localVarAxiosArgs.url,
        };
        return axios.request(axiosRequestArgs);
      };
    },
  };
};

/**
 * ReportingApi - factory interface
 * @export
 */
export const ReportingApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  return {
    /**
     *
     * @param {string} start date time iso string
     * @param {string} end date time iso string
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async reportingControllerHighestQueriedParamWithMovingOneHourBlock(
      start: string,
      end: string,
      options?: AxiosRequestConfig,
    ): Promise<AxiosResponse<TimeSeriesMostQueriedResponse>> {
      return ReportingApiFp(configuration)
        .reportingControllerHighestQueriedParamWithMovingOneHourBlock(
          start,
          end,
          options,
        )
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async reportingControllerRecentQueries(
      options?: AxiosRequestConfig,
    ): Promise<AxiosResponse<TimeSeriesMostQueriedResponse>> {
      return ReportingApiFp(configuration)
        .reportingControllerRecentQueries(options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {string} start
     * @param {string} end
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async reportingControllerTopQueries(
      start: string,
      end: string,
      options?: AxiosRequestConfig,
    ): Promise<AxiosResponse<TopQueriedParameterResponse>> {
      return ReportingApiFp(configuration)
        .reportingControllerTopQueries(start, end, options)
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * ReportingApi - object-oriented interface
 * @export
 * @class ReportingApi
 * @extends {BaseAPI}
 */
export class ReportingApi extends BaseAPI {
  /**
   *
   * @param {string} start date time iso string
   * @param {string} end date time iso string
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ReportingApi
   */
  public async reportingControllerHighestQueriedParamWithMovingOneHourBlock(
    start: string,
    end: string,
    options?: AxiosRequestConfig,
  ): Promise<AxiosResponse<TimeSeriesMostQueriedResponse>> {
    return ReportingApiFp(this.configuration)
      .reportingControllerHighestQueriedParamWithMovingOneHourBlock(
        start,
        end,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }
  /**
   *
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ReportingApi
   */
  public async reportingControllerRecentQueries(
    options?: AxiosRequestConfig,
  ): Promise<AxiosResponse<TimeSeriesMostQueriedResponse>> {
    return ReportingApiFp(this.configuration)
      .reportingControllerRecentQueries(options)
      .then((request) => request(this.axios, this.basePath));
  }
  /**
   *
   * @param {string} start
   * @param {string} end
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ReportingApi
   */
  public async reportingControllerTopQueries(
    start: string,
    end: string,
    options?: AxiosRequestConfig,
  ): Promise<AxiosResponse<TopQueriedParameterResponse>> {
    return ReportingApiFp(this.configuration)
      .reportingControllerTopQueries(start, end, options)
      .then((request) => request(this.axios, this.basePath));
  }
}
