/* tslint:disable */
/* eslint-disable */
/**
 * Weather Forecast and Traffic Monitoring
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { TrafficCamDataResponse } from '../models';
/**
 * TrafficCamApi - axios parameter creator
 * @export
 */
export const TrafficCamApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} [dateTime] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        trafficCamControllerGet: async (dateTime?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/traffic-cameras`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (dateTime !== undefined) {
                localVarQueryParameter['date_time'] = dateTime;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TrafficCamApi - functional programming interface
 * @export
 */
export const TrafficCamApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} [dateTime] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async trafficCamControllerGet(dateTime?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<TrafficCamDataResponse>>> {
            const localVarAxiosArgs = await TrafficCamApiAxiosParamCreator(configuration).trafficCamControllerGet(dateTime, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * TrafficCamApi - factory interface
 * @export
 */
export const TrafficCamApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @param {string} [dateTime] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async trafficCamControllerGet(dateTime?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<TrafficCamDataResponse>> {
            return TrafficCamApiFp(configuration).trafficCamControllerGet(dateTime, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * TrafficCamApi - object-oriented interface
 * @export
 * @class TrafficCamApi
 * @extends {BaseAPI}
 */
export class TrafficCamApi extends BaseAPI {
    /**
     * 
     * @param {string} [dateTime] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TrafficCamApi
     */
    public async trafficCamControllerGet(dateTime?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<TrafficCamDataResponse>> {
        return TrafficCamApiFp(this.configuration).trafficCamControllerGet(dateTime, options).then((request) => request(this.axios, this.basePath));
    }
}
